name: shop_app_mobile
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  rxdart: ^0.27.7
  animate_do: ^3.0.2
  animations: ^2.0.7
  device_info_plus: ^8.2.0
  geolocator: ^10.1.0
  flutter_secure_storage: 8.0.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  uuid: ^3.0.7
  pin_code_fields: ^8.0.1
  intl: ^0.18.1
  dio: ^5.2.1+1
  dio_cache_interceptor: ^3.5.0
  http: ^1.1.0
  permission_handler: ^10.4.1
  connectivity_plus: ^4.0.1
  dio_smart_retry: ^6.0.0
  lottie: ^3.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app-icon.png"


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/animations/
    - assets/font/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/font/DMSans-Bold.ttf
          weight: 700
        - asset: assets/font/DMSans-SemiBold.ttf
          weight: 600
        - asset: assets/font/DMSans-Regular.ttf
          weight: 400
    
